import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import { useEffect, useState } from 'react'
import axios from 'axios';
import { CopyToClipboard } from 'react-copy-to-clipboard';
import Router, { useRouter,withRouter } from "next/router";
import toast, { Toaster } from 'react-hot-toast';


export default function Home() {
  // axios.defaults.withCredentials = true;
  const baseUrl = "animeta.aucfan-cn.com"
  const router = useRouter();
  const pageStyle = {
    duration: "tw-text-1xl tw-text-gray-400 tw-place-self-center tw-text-center",
    title: "tw-text-4xl",
    boxContainer: ""
  }

  const [showModal, setShowModal] = useState(false)
  const [inviteHistory, setInviteHistory] = useState([])
  const [invitedAmount, setInvitedAmount] = useState(0)
  const [uuid,setUuid] = useState<String|String[]|undefined>()
  const [copied,setCopied] =useState(Boolean)



  const getInvitHistory = (uuid: String|String[]|undefined) => {
    axios.get(`http://${baseUrl}/index/inviting/get_record_of_invitation?uuid=${uuid}`, {
    })
      .then(
        // 后台验证通过，返回用户信息
        // 前端接收并登陆系统  
        res => {
          console.log(res.data)
          setInviteHistory(res.data.data.list)
          let invitedAmount = 0
          res.data.data.list.map((item: { status: number; }) => {
            // console.log(item)
            item.status == 1 ? invitedAmount += 1 : null
          })
          setInvitedAmount(invitedAmount)
        }
      )
      .catch(
      // 验证失败    
    )

  }

  useEffect(() => {

    uuid&&getInvitHistory(uuid)
  }, [uuid])

  useEffect(() => {
    if(!router.isReady) return;

    console.log(router.query.uuid)
    setUuid(router.query.uuid)
  }, [router.isReady])

  return (
    <div className="tw-bg-black tw-place-items-center  tw-min-h-screen tw-flex tw-justify-center">
      <Toaster />
      <Head>
        <title>邀请有礼 Animeta</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <meta http-equiv="Content-Security-Policy" content="upgrade-insecure-requests"></meta>
      </Head>

      <main className="tw-flex-row tw-right-1 lg:tw-max-w-[500px] tw-mb-4">
        <div className='tw-w-full tw-flex tw-justify-end'>
          {!showModal && <div className='tw-relative tw-w-12 tw-top-10 tw-right-4 tw-z-10 tw-bg-gray-500/50 tw-rounded-lg tw-text-white tw-px-2 tw-py-1 hover:tw-cursor-pointer' onClick={(() => { setShowModal(true) })}>
            <p>详情</p>
          </div>}
        </div>


        <div className="tw-flex tw-place-content-center">
          <div className='tw-flex tw-flex-col tw-absolute tw-place-self-center tw-z-10'>
            <div className='tw-flex tw-flex-col'>
              <div className={pageStyle.duration}>
                <h2 >活动时间：12月10日-12月17日</h2>
                <Image src={'./img/invite_text.png'} alt='' width={300} height={300} />
              </div>
              <div className='tw-place-self-center motion-safe:tw-animate-bounce ' style={{ animationDuration: "1.5s" }} >
                <Image className=' tw-animate-ping tw-absolute' src='./img/box.png' width={200} height={200} alt="" style={{ animationDuration: "1.5s", animationDelay: "0.75s" }} />
                <Image className='tw-relative tw-z-1' src={'./img/box.png'} width={200} height={200} alt="" />
              </div>

            </div>

            <div className=' tw-p-1 tw-bg-gray-400/50 tw-rounded-lg'>
              <p className='tw-text-xs tw-text-white'>
                每两位好友通过您的邀请并完成活动，您将获得一个盲盒
              </p>
            </div>
            <div className="tw-z-20 tw-mt-10 tw-place-self-center ">
              <CopyToClipboard text={`http://h5.animeta.aucfan-cn.com/register?uuid=${uuid}`}
                onCopy={() => setCopied(true)}>
                <button className="tw-z-20 tw-ds-btn tw-glass tw-ds-btn-info tw-text-white" onClick={()=>{toast.success('复制邀请链接成功!快去分享给好友吧~')}}>立即邀请
                  <Image className='tw-relative' src={'./img/link_icon.png'} width={20} height={20} alt="" />
                </button>
              </CopyToClipboard>

            </div>
          </div>
          <div >
            <Image className='tw-animate-pulse tw-z-0' src={'./img/text_bg_img.png'} width={500} height={500} alt="" style={{ animationDuration: "1.5s", animationDelay: "3s" }} />
          </div>
        </div>




        <div className='tw-text-white tw-flex tw-flex-row  tw-w-full tw-justify-center tw-divide-x tw-divide-gray-300/50 '>
          <div className='tw-flex tw-flex-col  tw-w-[150px] tw-px-4'>
            <p className='  tw-self-center'>
              已邀请人数
            </p>
            <div className='tw-flex tw-flex-row tw-self-center'>
              <p className='tw-text-3xl'>{inviteHistory.length}/</p>
              <p className='tw-text-sm tw-self-end'>人</p>
            </div>
          </div>

          <div className='tw-flex tw-flex-col tw-w-[150px]  tw-px-4'>
            <p className='  tw-self-center'>
              已获得盲盒数
            </p>
            <div className='tw-flex tw-flex-row tw-self-center'>
              <p className='tw-text-3xl'>{invitedAmount}/</p>
              <p className='tw-text-sm tw-self-end'>个</p>
            </div>
          </div>
        </div>

        <div className='tw-mt-10 tw-text-white tw-flex tw-justify-center'>
          <div className='tw-flex tw-flex-row '>
            <Image className='tw-relative' src={'./img/shell_icon.png'} width={20} height={20} alt="" />
            <p>邀请记录</p>
            <Image className='tw-relative' src={'./img/shell_icon.png'} width={20} height={20} alt="" />
          </div>

        </div>
        <div className='tw-w-full tw-text-gray-300 tw-text-xl tw-mt-4 tw-px-4'>

          {
            inviteHistory&&inviteHistory.map((item:{nickname:String,avatar_url:string,uuid:String,status:boolean,register_time:String}, index) => (
              <div key={index} className='tw-flex tw-flex-row tw-justify-between tw-items-center tw-space-x-1 '>
                <div className='tw-flex tw-flex-row tw-space-x-3 tw-items-center '>
                  <p>{index +1}</p>
                  <Image className='tw-w-6 tw-h-6 tw-rounded-full tw-ring-1 tw-ring-white' src={item.avatar_url} alt="" />
                  <div className='tw-flex tw-flex-col tw-text-sm'>
                    <p>{item.nickname}</p>
                    <p>{item.uuid.slice(0, 5)}...{item.uuid.slice(-5, -1)}</p>
                  </div>
                </div>

                <div className='tw-flex tw-flex-col tw-text-sm'>
                  {item.status ? <p className='tw-text-right tw-text-blue-500  '>已充值</p> : <p className='tw-text-right tw-text-gray-500  '>未充值</p>}
                  {/* <p className='tw-text-right tw-text-blue-500  '>已充值</p> */}
                  <p>{item.register_time.slice(0,-3)}</p>

                </div>
              </div>
            ))
          }

          {showModal && <div className='tw-fixed tw-w-full tw-h-full tw-right-0 tw-top-0 tw-z-50 tw-bg-black/70 tw-flex tw-justify-center' onClick={(() => { setShowModal(false) })}>
            <div className='lg:tw-w-[500px] tw-h-screen'>
              <div className='tw-flex tw-justify-end'>
                <button className="tw-bg-gray-500/60 tw-rounded-full tw-right-3 tw-p-1 tw-mt-8 tw-mx-6" onClick={(() => { setShowModal(false) })}>
                  <svg xmlns="http://www.w3.org/2000/svg" className="tw-h-6 tw-w-6" fill="none" viewBox="0 0 24 24" stroke="currentColor"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M6 18L18 6M6 6l12 12" /></svg>
                </button>
              </div>
              <div>

                <p className='tw-p-4'>活动详情：
                </p>
                <p  className='tw-px-4'>
                每邀请2名有效新用户注册平台，既可获得NFT盲盒1个，多邀多得，以此类推。（注：新用户在平台充值≥1USDT即可算成效用户）--ANIMETA
                </p>

              </div>

            </div>

          </div>}
        </div>
      </main>
    </div>
  )
}
